# El CustomModelData Id del totem animado que se ha configurado en el paquete de recursos
totem-model-id: 0

# Retraso en ticks para mostrar los efectos de bienvenida (animación, sonidos, textos)
# 20 ticks == 1 segundo
# Pocos ticks pueden hacer que el usuario no vea la animación debido a la pantalla de carga
join-delay-ticks: 40

title:
  enabled: true
  text: "&e!Bienvenido!"
  subtitle: "&f%player_name%"
  # --------
  # Tiempos en ticks
  fade-in: 10
  stay: 60
  fade-out: 10

chat-message:
  enabled: true
  message:  |
    &f========================
    &e Bienvenido a nuestro servidor
    &f========================

join-sound:
  enabled: true
  sound-key: "minecraft:entity.player.levelup"
  volume: 1.0
  pitch: 1.0